export const TODO_ADD = 'TODO_ADD';
export const TODO_CHANGE = 'TODO_CHANGE';
export const TODO_DELETE = 'TODO_DELETE';
export const TODO_UPDATE = 'TODO_UPDATE';
export const TODO_TOGGLE_ALL_COMPLETED = 'TODO_TOGGLE_ALL_COMPLETED';
export const TODO_FILTER_CHANGE = 'TODO_FILTER_CHANGE';